version: "3"
services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "3000:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    node-app:
        build: .
        container_name: node-app-container
        ports:
            - "3000-3001:3000"
        environment:
            - PORT=3000
        depends_on:
            - mongo
    mongo:
        image: mongo
        container_name: mongo-container
        environment:
            - MONGO_INITDB_ROOT_USERNAME=nabeshi
            - MONGO_INITDB_ROOT_PASSWORD=mypassword
        volumes:
            - mongo-db:/data/db
    redis:
        image: redis
        container_name: redis-container
volumes:
    mongo-db: